[book]
authors = ["Krzysztof Kowalczyk"]
language = "pl"
multilingual = false
src = "src"
title = "Jak zacząć karierę jako developer"
license = "MIT OR Apache-2.0"

# enable preprocessors:

# [preprocessor.index]

[preprocessor.links]

# output-related options:

[output.html.search]
limit-results = 10
