[book]
authors = ["Krzysztof Kowalczyk"]
language = "pl"
multilingual = false
src = "src"
title = "Jak zacząć karierę jako developer"
license = "CC BY 4.0"

# enable preprocessors:

# [preprocessor.index]

[preprocessor.links]

# output-related options:

[output.html]
site-url = "https://kowaalczyk.github.io/dev-kariera/"
git-repository-url = "https://github.com/kowaalczyk/dev-kariera"

[output.html.search]
limit-results = 10
